### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by chrisnorth** [jkanner/streamlit-audio#4]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://jkanner-streamlit-audio-app-86e0z3.streamlitapp.com/jkanner/streamlit-audio/main/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

(^ default message from streamlit!)

**Comment by jkanner** [comment]
Thanks, @chrisnorth .  I made an attempt to fix this, and it seems to be running now.  Please let me know if the problem comes up again.
