### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by Stefania2** [jkanner/streamlit-audio#5]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://jkanner-streamlit-audio-app-86e0z3.streamlit.app/jkanner/streamlit-audio/main/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by jkanner** [comment]
@Stefania2  Thank you!  I'm sorry I missed this note in April.  I checked this app, and it seems OK right now.
